export class EmbarqueModel {
    constructor(
        public idembarque: number,
        public fecharealizacion: string,
        public importacion_exportacion: number,
        public idtipoembarque: number,
        public gestion: number,
        public correlativo: number,
        public embarque: string,
        public idcliente: number,
        public cliente: string,
        public numeroguia: string,
        public idciudad: number,
        public idusuario: number,
        public nombre: string,
        //public valordeclarado: string,
        public descripcioncarga: string,
        public carpetapacena: string,
        public servicio_logistico: boolean,
        public peso: number,
        public volumen: string,
        public piezas: number,
        public idtipobulto: number,
        public nodui: string,
        public noidentificacion: string,
        public idincoterms: number,
        public finalizado: boolean,
        public fechafinalizacion: string,
        //public idtipoexpedidor: number,
        public idexpedidor: string,
        public idexpedidordireccion: number,
        //public idtipoultimoconsignatario: number,
        public idultimoconsignatario: string,
        public idultimoconsignatariodireccion: number,
        //public idtipoentidadnotificar: number,
        //public identidadnotificar: string,
        //public identidadnotificardireccion: number,
        //public idagentecarga: number,
        //public idagentecargadireccion: number,
        //public idagentedestino: number,
        //public idagentedestinodireccion: number,
        public idmediotransporte: number,
        public idtipocarga: number,
        public idtransportista: number,
        public numerovehiculo: string,
        public idsalida: number,
        public fechasalida: string,
        public idarribo: number,
        public fechaarribo: string,
        public idorigen: number,
        public iddestino: number,
        public idhorario: number,
        public idtemperatura: number,
        public numero_precinto: string,
        public estibadoresSLG: number,
        public estibadores: number,
        public costo_operador_transporte: number,
        public costos: [{
            idcosto: number,
            idconcepto: number,
            concepto: string,
            concepto_ovp: string,
            id_OVPRef: string,
            cantidad: number,
            monto: number,
            iddivisa: number,
            codigodivisa: string,
            tipocambio: number,
            tipocambious: number,
            idtipodestinatario: number,
            iddestinatario: number,
            identidad: string,
            destinatario: string,
            notas: string,
            esagente: boolean,
            idfacturanotadebito: number,
            documento: string,
            facturanotadebito: string,
            idestadofacturanotadebito: number,
            idordenservicioe: number,
            tienedocumento: boolean,
            factura: string,
            nota_entrega: string,
            usuario: string,
            created_at: string
        }],
        public cargos: [{
            idcargo: number,
            idconcepto: number,
            concepto: string,
            concepto_ovp: string,
            id_OVP: number,
            cantidad: number,
            monto: number,
            iddivisa: number,
            codigodivisa: string,
            tipocambio: number,
            tipocambious: number,
            idtipodestinatario: number,
            iddestinatario: number,
            identidad: string,
            destinatario: string,
            notas: string,
            esagente: boolean,
            idfacturanotadebito: number,
            documento: string,
            facturanotadebito: string,
            idestadofacturanotadebito: number,
            idplanilla: number,
            idinvoice: number,
            idordenservicioi: number,
            tienedocumento: boolean,
            factura: string,
            iddestinocargo: number,
            destinocargo: string,
            usuario: string,
            created_at: string
        }],
        public eventos: [{
            idevento: number,
            idtipoevento: number,
            tipoevento: string,
            fecharegistro: string,
            fechaplanificada: string,
            con_observacion: boolean,
            ideventodescripcion: number,
            eventodescripcion: string,
            evento: string,
            idusuario: number,
            nombre: string,
            enviado: boolean
        }],
        public correosembarque: [{
            idcorreosembarque: number,
            correo: string
        }],
        public documentosembarque: [{
            iddocumento: number,
            documento: string
        }],
        public facturas: [{
            idfactura: number,
            iddocumento: string,
            numero: number,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public notascobranza: [{
            idnotadebito: number,
            iddocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public facturaspago: [{
            idfacturapago: number,
            iddocumento: string,
            tipodocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public planillas: [{
            idplanilla: number,
            iddocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public invoices: [{
            idinvoice: number,
            iddocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public ordenserviciosi: [{
            idordenservicioi: number,
            iddocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }],
        public ordenserviciose: [{
            idordenservicioe: number,
            iddocumento: string,
            numero: string,
            fecha: string,
            monto: number,
            idestado: number,
            estado: string
        }]
        //public cargos: Array<any>
    ){}
}
