export class IngresoModel {
    constructor(
        public idingreso: number,
        public idalmacen: number,
        public numero: number,
        public gestion: number,
        public numeroingreso: string,
        public idcliente: number,
        public cliente: string,
        public es_vehiculo: boolean,
        public idcliente_destino: number,
        public cliente_destino: string,
        public envio_api: string,
        public respuesta_api: string,
        public reportado_api: boolean,
        public fecha: string,
        public placa: string,
        public contenedor: string,
        public idtipoingreso: number,
        public tipoingreso: string,
        public precinto: string,
        public idtipodescarga: number,
        public tipodescarga: string,
        public idtipocamion: number,
        public tipocamion: string,
        public idtipocontenedor: number,
        public tipocontenedor: string,
        public idtipoproducto: number,
        public tipoproducto: string,
        public piezas_manifestadas: string,
        public peso_total: number,
        public proveedor: string,
        public no_contrato: string,
        public delivery_batch: string,
        public rubro_producto: string,
        public project: string,
        public invoice: string,
        public dui: string,
        public cantidad_pallet: number,
        public cantidad_cajas: string,
        public hora_inicio: string,
        public hora_fin: string,
        public cantidad_estibadores: number,
        public nota_adicional: string,
        public fechasistema: string,
        public idusuario_recibido: number,
        public usuario_recibido: string,
        public ci_recibido: string,
        public nombre_entrega: string,
        public ci_entrega: string,
        public empresa_entrega: string,
        public partida: string,
        public fecha_cierre_transito: string,
        public fecha_emision_parte: string,
        public idsalida_origen: number,
        public detalle: [{
            idingresodetalle: number,
            codigo: string,
            serie: string,
            descripcion: string,
            centro_distribucion: string,
            //sustanciascontroladas: boolean,
            categoria: string,
            cantidad: number,
            cantidad_saldo: number,
            idembalaje: number,
            codigoembalaje: string,
            lote: string,
            costo_un: number,
            //cantidad_no_conf: number,
            idno_conf: number,
            idclasificacion: number,
            idmerma: number,
            //fechaproduccion: string,
            fechavencimiento: string,
            relacion_caja: string,
            volumen: number,
            peso: number,
            pallet: string,
            peso_saldo: number,
            temperatura: string,
            iddoc_errada: number,
            doc_errada: string,
            observaciones: string,
            idalmacendetalle: number,
            ubicacionalmacen: string,
            dividido: number,
            factor_conversion: number,
            codigoembalaje_salida: string,
            salidas: Array<any>,
            cantidadextraida: number,
            pesoextraido: number,
            bultosextraidos: number,
            cantidad_no_confextraidos: number,
            modelo: string,
            marca: string,
            color: string,
            partida_especifica: string,
            invoice: string,
            no_dim: string,
            fecha_pase_salida: string,
            accesorios_vehiculos: Array<any>
        }],
        public adjuntos: [{
            iddocumento: number,
            documento: string
        }]
    ){}
}
