export class InventarioModel {
    constructor(
        public idingresodetalle: number,
        public idingreso: number,
        public idcliente: number,
        public cliente: string,
        public numeroingreso: string,
        public fechaingreso: Date,
        
        public placa: string,
        public contenedor: string,
        public idtipoingreso: number,
        public tipoingreso: string,
        public precinto: string,
        public idtipodescarga: number,
        public tipodescarga: string,
        public idtipocamion: number,
        public tipocamion: string,
        public idtipocontenedor: number,
        public tipocontenedor: string,
        public idtipoproducto: number,
        public tipoproducto: string,
        public piezas_manifestadas: string,
        public peso_total: number,
        public proveedor: string,
        public no_contrato: string,
        public delivery_batch: string,
        public rubro_producto: string,
        public project: string,
        public invoice: string,
        public dui: string,
        public cantidad_cajas: number,
        public hora_inicio: string,
        public hora_fin: string,
        public cantidad_estibadores: string,
        public nota_adicional: string,
        public idusuario_recibido: number,
        public usuario_recibido: string,
        public fechasistema: Date,
        public nombre_entrega: string,
        public ci_entrega: string,
        public empresa_entrega: string,
        
        
        public codigo: string,
        public codigolote: string,
        public serie: string,
        public descripcion: string,
        //public sustanciascontroladas: boolean,
        public categoria: string,
        public cantidad: number,
        public idembalaje: number,
        public codigoembalaje: string,
        public lote: string,
        public costo_un: number,
        public cantidad_no_conf: number,
        public idno_conf: number,
        public no_conf: string,
        public idmerma: number,
        public merma: string,
        //public fechaproduccion: Date,
        public fechavencimiento: Date,
        public diasavencer: number,
        public volumen: number,
        public bultos: number,
        public peso: number,
        public pallet: string,
        public temperatura: string,
        public observaciones: string,
        
        public idalmacendetalle: number,
        public ubicacionalmacencorto: string,
        public ubicacionalmacen: string,
        
        public salidaspendientes: [{
            idalida: number,
            numero: number,
            gestion: number,
            fecha: Date
        }]
        
    ){}
}