export class SalidaDetalleModel {
    constructor(
        public idsalidadetalle: number,
        public idsalida: string,
        public idingresodetalle: number,
        public codigo: string,
        public serie: string,
        public categoria: string,
        public descripcion: string,
        public centro_distribucion: string,
        public fechavencimiento: string,
        public diasavencer: number,
        public lote: string,
        public costo_un: number,
        public cantidad_no_conf: number,
        public cantidad_no_confactual: number,
        public no_conf: string,
        public merma: string,
        public factor_conversion: number,
        public relacion_caja: string,
        public cantidad: number,
        public cantidadactual: number,
        public idembalaje: number,
        public embalaje: string,
        public codigoembalaje: string,
        public codigoembalaje_salida: string,
        public peso: number,
        public pesoactual: number,
        public bultos: number,
        public bultosactual: number,
        public temperatura: string,
        public modelo: string,
        public marca: string,
        public color_vehiculo: string,
        public observaciones: string,
        public ubicacionalmacen: string,
        public numeroingreso: string,
        public centro_rubro: string,
        public kilometraje: string,
        public tiene_danios: boolean,
        public danios: string,
        public tiene_faltante: boolean,
        public faltante: string,
        public imagenes: number,
        public con_accesorios: boolean,
        public accesorios_vehiculos: Array<any>
    ){}
}
