import {SalidaDetalleModel} from 'src/app/models/salidaDetalle.model';

export class SalidaModel {
    constructor(
        public idsalida?: string,
        public numero?: number,
        public gestion?: number,
        public numerosalida?: string,
        //public idalmacen: number,
        public codigo_almacen?: string,
        public almacen?: string,
        public idcliente?: string,
        public cliente?: string,
        public es_vehiculo?: boolean,
        public movimiento?: boolean,
        public es_no_conf?: boolean,
        public idpedido?: string,
        public fecha?: string,
        public solicitado_por?: string,
        public autorizado_por?: string,
        public idmovilizador?: number,
        public movilizador?: string,
        public delivery_note?: string,
        public proyecto_no?: string,
        public contrato_no?: string,
        public rubro_producto?: string,
        public ciudad?: string,
        public direccion_entrega?: string,
        public idalmacen_destino?: number,
        public codigo_almacen_destino?: string,
        public transporte?: string,
        public placa?: string,
        public cantidad_pallet?: number,
        public cantidad_cajas?: number,
        public autorizacion_compra?: string,
        public tipo_pedido?: string,
        public almacen_destino?: string,
        public pedido_consolidado?: string,
        public partida?: string,
        public hora_inicio_a?: string,
        public hora_fin_a?: string,
        public cantidad_estibadores_a?: number,
        public hora_inicio_cable?: string,
        public hora_fin_cable?: string,
        public nota_adicional?: string,
        public hora_inicio_b?: string,
        public hora_fin_b?: string,
        public cantidad_estibadores_b?: number,
        public idusuario_entrega?: number,
        public nombre_entrega?: string,
        public ci_entrega?: string,
        public nombre_recibido?: string,
        public ci_recibido?: string,
        public empresa_recibido?: string,
        public fecha_recibido?: string,
        public entrega_a_tiempo?: boolean,
        public entrega_completa_conforme?: boolean,
        public finalizado?: boolean,
        public idingreso?: number,
        public detalle?: Array<SalidaDetalleModel>,
        public adjuntos?: [{
            iddocumento: number,
            documento: string
        }]
    ){}
}
