export class TimbradoModel {
    constructor(
        public idtimbrado: number,
        public idcliente: number,
        public cliente: string,
        public created_at: string,
        public detalle: [
            {
            idtimbradodetalle: number,
            timbradoturno: string,
            diasemana: string,
            fecha: string,
            codigo_producto: string,
            sku: string,
            nro_tcf: string,
            factura_timbrada: string,
            cantidad_timbrado: number,
            cantidad_paquetes_timbrado: number,
            meta_timbrado: number,
            cumplimiento: number,
            umcompra: number,
            umalterna: number,
            total_unidades: number,
            precio_timbrado: number,
            precio_por_timbre: number,
            metodo: string,
            precio_metodo: number,
            precio_total: number,
            precio: number,
            observaciones: string,
            personal: number,
            lotes_permiso_senasag: string,
            faltantes_senasag: number,
            lote_senasag: string,
            faltante: number,
            lote_faltante: string,
            danados: number,
            lote_danados: string,
            quebrados: number,
            lote_quebrados: string,
            sin_tapa: number,
            lote_sin_tapa: string,
            borrosos: number,
            lote_borrosos: string,
            film: number,
            cinta: number,
            silicona: number,
            hora_hinicio: string,
            hora_fin: string,
            horas_trabajadas: string,
            timbres_sobrantes: number
        }
        ]
    ){}
}
